services:
  ai_chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_chat
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ai_chat_network
    command: >
      sh -c "python src/store_data.py && chainlit run -w src/main.py --host 0.0.0.0"

  postgres:
    image: ankane/pgvector
    container_name: postgres_pgvector
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ai_chat_network

volumes:
  postgres_data:

networks:
  ai_chat_network:
    driver: bridge